handle STS failures gracefully

diff --git a/nubis/bin/sts b/nubis/bin/sts
--- a/nubis/bin/sts
+++ b/nubis/bin/sts
@@ -3,7 +3,18 @@
 ROLE=$1
 shift
 
+if [ "$BUILD_TAG" = "" ]; then
+  BUILD_TAG=cli
+fi
+
 OUTPUT=`aws sts assume-role --role-arn "$ROLE" --role-session-name "$BUILD_TAG"`
+
+STATUS=$?
+
+if [ "$STATUS" != "0" ]; then
+  echo "STS Failure: $OUTPUT"
+  exit $STATUS
+fi
 
 export AWS_ACCESS_KEY_ID=`echo $OUTPUT | jq -r '.Credentials.AccessKeyId'`
 export AWS_SECRET_ACCESS_KEY=`echo $OUTPUT | jq -r '.Credentials.SecretAccessKey'`
